name: DailyLife
version: '1.0.0'
main: nl.openminetopia.DailyLife
api-version: '1.21'
loader: nl.openminetopia.DailyLifeLoader
authors: [ '_GamingSkill' ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: true
    Vault:
      required: false
    Skript:
      load: BEFORE
      required: false
    Citizens:
      load: BEFORE
      required: false
    FancyNpcs:
      load: BEFORE
      required: false
    LabyModServerAPI:
      load: BEFORE
      required: false